### ISSUE TITLE
Can't compile the code.

### ISSUE THREAD

**Issue by DmitRex** [ValveSoftware/source-sdk-2013#263]
Hello,
I tried to compile sp code with both VS 2010 Express and 2012 Express but I keep getting this error:
"fatal error C1010: unexpected end of file while looking for precompiled header"
file: "pointeroverride.asm"
and lots of C2018, C2059, C2086, C2143,C2146, C4430 errors pointing at that "pointeroverride.asm" file.
Please, help.

**Comment by tschumann** [comment]
Extremely late reply, but you need to change vpc_scripts/source_dll_win32_base.vpc and vpc_scripts/source_exe_win_win32_base.vpc
Change the following:
$CommandLine                            "$QUOTE$(VCInstallDir)bin\ml.exe$QUOTE /c /Cp /Zi /Fo$QUOTE$(IntDir)\$(InputName).obj$QUOTE $QUOTE$(InputPath)$QUOTE"
to
$CommandLine                            "$QUOTE$(VC_ExecutablePath_x64_x86)\ml.exe$QUOTE /c /Cp /Zi /Fo$QUOTE$(IntDir)\$(InputName).obj$QUOTE $QUOTE$(InputPath)$QUOTE"
The path to ml.exe seems to have changed.

**Comment by DmitRex** [comment]
Thanks. The issue is long irrelevant to me, but I guess your answer might help someone else with similar issue.

**Comment by Gchipunov** [comment]
when trying to compile source-shader-editor get same issue, anouther solution hacky, is to copy ml.exe to that folder , similar problem with compiling libcurl on windows 7 with windows 8 sdk, had to throw away the .res file because cvtres.exe was just broken , problably a problem with .net not all updated on windows 7. the reason need compile libcurl on windows 7 is because of newer version on tls 1.3 is supported on like discord api.
