### ISSUE TITLE
Linux Compile on Ubuntu 14

### ISSUE THREAD

**Issue by BerntA** [ValveSoftware/source-sdk-2013#310]
Whenever I launch my mod using Linux Ubuntu it says 'Engine Error: Unable to load library client'? 
I've included FMOD Sound System in my mod and I've added it as ImpLib, everything compiles fine. (I have also included the .so file in my bin folder for fmod) But that is the only suspicion I have or perhaps I've missed a step? I've not used the Steam Client Run time, I'm not entirely sure what I'm supposed to use the runtime for.

**Comment by LestaD** [comment]
Do you copy your client.so* and server.so* files to steamapps/sourcemods/{yourmod}/bin directory?

**Comment by BerntA** [comment]
Yeah

**Comment by LestaD** [comment]
Try debug with gdb

**Comment by bmk10** [comment]
I have same issue, when I pull the newest code from source-sdk-2013 github, but my old compile of mod  run fine... by this I mean, the current version (lastest on github), doing a a compile of client.so and server.so I get this error also unable to 'Engine Error: Unable to load library client' , I am thinking its you that is responsible for this issue, earlier version of source-sdk-2013 from github worked for me, I would have to double check my compile of 'clean' (source-sdk-2013) from github from more than 5 months ago(I remember that working), vs the one on here right now.. so my mod works but clean new version off current github doesn't so there is a problem I believe.. the reason I noticed this is because 6 months ago  I compiled CrimeWars2014 on my virtual linux machine, so I had accesss to windows the whole time to do google searches .. etc ( convince, to get gdb to work with qt creator) , now that I have a little linux box, I wanted to do more testing on a crappy computer that gets more than virtual machine (10 fps) and my little box gets 20fps or 10-30 fps, depending on map

**Comment by bmk10** [comment]
because first on mac and linux, I compile the original github source-sdk-2013 version, check that it compiles( all the related issues, gc++ libs installing, random linux/mac hassles, theres some undocumented ones, like being a linux guru, and mac physcopath) other than that , after I compile the original, I go to compiling my mod.. there is other issues to note like mac and linux .so files are 32 bit and can't load as many mdl files or maybe texture file too before showing 'Error Models' on linux and crashing from not enough memory on mac.., I may post this in anouther issue though, just need to note it..

**Comment by bmk10** [comment]
unless there is a hash on steam blocking the original source sdk 2013 from working on linux client libirary its most likely something new in the code or something..

**Comment by BerntA** [comment]
This issue has been solved, I didn't put the fmod.so file in the right folder...

**Comment by rlabrecque** [comment]
Please close the issue then!
