### ISSUE TITLE
Master servers rejecting "beta_test"

### ISSUE THREAD

**Issue by dotn3b** [ValveSoftware/source-sdk-2013#350]
The Steam master servers are rejecting servers from the `beta_test` branch:

    MasterRequestRestart
    Your server needs to be restarted in order to receive the latest update.
    Your server needs to be restarted in order to receive the latest update.

The version seems to be misconfigured:
```
] version
Build Label:                 0   # Uniquely identifies each build
Network PatchVersion:    valve   # Determines client and server compatibility
Protocol version:           24   # High level network protocol version
Server version:              0
Server AppID:           243750
```

`Client version` and `Client AppID` are the same as the ones displayed for the server above.
Tested with GNU/Linux and Windows versions.

**Comment by danielmm8888** [comment]
We've been pestering various people at Valve ( especially EricS ) ever since this issue arose back at the begining of September, however they've yet to respond to any of us. 

This has been a huge issue for us ( and anybody else running the beta_test branch, which is a worryingly small amount of people, as most still seem to use the 'upcoming ' branch ) however Valve has shown 0 incnentice to fix it.

**Comment by gamenew09** [comment]
I've seen this on my mod as well, while that isn't important for me yet. This still needs to be fixed on Valve's end ASAP.

**Comment by danielmm8888** [comment]
By the way, here is what the "version" ConCommand prints out for both "upcoming" and "beta_test" respectively.

http://pastebin.com/v753dDHt

**Comment by Nephyrin** [comment]
This will be fixed with the next update to the SDK Base, which we're hoping to get out shortly.

**Comment by dotn3b** [comment]
Thank you.

**Comment by danielmm8888** [comment]
Could you please provide a reason as to why this issue took this long to fix?

**Comment by Nephyrin** [comment]
If you are seeing this issue on the current beta_test branch, can you please post the steam.inf your mod is using, if any? The output doesn't quite match what happens when using sourcetest, and I suspect mods may be using an outdated steam.inf format.

**Comment by NFMynster** [comment]
I'm on the upcoming build and I can see my dedicated servers in the server browser.
I do not get that message about the server needed to restart.
You gotta set Source SDK Base 2013 Dedicated Server to upcoming as well in Steam.

**Comment by danielmm8888** [comment]
The upcoming build does work, however at this point it's pretty dangerous to be using the upcoming build.

Also, my mod is using the default steam.inf that comes with the Source 2013 MP Base on the beta_test branch.

**Comment by NFMynster** [comment]
Why is it dangerous to use? I did not know that!

**Comment by danielmm8888** [comment]
There is an exploit which allows anybody to execute malicious code via sound files. The malicious sound files can be in any form (sound sprays, custom maps with that sound, etc).

This exploit has affected our mod TF2C, and CS:S back at the beginning of September. A group of people made a sound file which downloaded and executed a RAT on any client that downloaded the sound file and or map.

**Comment by NFMynster** [comment]
Is that via the multiplayer ingame menu tab that the files are uploaded?

**Comment by danielmm8888** [comment]
Yes. You could "'fix" this on upcoming by just disabling all uploads and downloads.

**Comment by NFMynster** [comment]
Thank you for the information.

**Comment by dotn3b** [comment]
I'm also using the default steam.inf from the hl2 subdirectory, that is not from mod directory itself.
````
PatchVersion=2954332
ClientVersion=2954332
ServerVersion=2954332
ProductName=sdk2013mp
appID=243750
ServerAppID=244310
````
The hl2 dir is in my game path: `game	|all_source_engine_paths|hl2`.

**On a hunch I copied the steam.inf into my mod directly**, like we had to do back with the *2007 SDK Base* for different reasons **and that made the game load up the version info correctly!**

**Comment by neico** [comment]
It's best to leave out the version entries when you copy the file to the mod folder.
At least on Source2007 it worked like that (where I assume that steam went and looked up the steam.inf on the appID to get the missing entries, alas a fallback)

Otherwise you're prone to get your mod outdated the moment a update arrives...

**Comment by dotn3b** [comment]
Those version entries are the exact issue here though. They are what's required to be present - specifically `PatchVersion` for the master server issue. If you copy the file over to your mod as a work-around until @Nephyrin fixes the actual issue, **do not** leave out the version entries. Otherwise it would be pointless.

**Comment by Nephyrin** [comment]
I see, I was testing a slightly different setup so I wanted to ensure we were seeing the same thing. The issue is simply that the engine now loads steam.inf before gameinfo.txt, so expects steam.inf to be in the MOD directory.

As a workaround, copying steam.inf into your mod directory should work fine. This is obviously less than ideal for SDK purposes, so we should have a better fix out shortly.

**Comment by Nephyrin** [comment]
A fix for this is on the beta_test branch now. Let me know if you're still seeing weirdness.

**Comment by dotn3b** [comment]
It's working, thank you!
