### ISSUE TITLE
Any Source SDK update?

### ISSUE THREAD

**Issue by mintchoco0122** [ValveSoftware/source-sdk-2013#500]
I should use old version of Visual Studio, but I want to use 2019. Do you think valve will update this SDK someday? When? Also, is there a way to release on Visual Studio 2019(v142)?

**Comment by GamerDude27** [comment]
The only way to use VS2019 at the moment is by having both VS2013 and VS2019 installed at the same time*.
Once you have them both installed, you can either manually change all the projects in your solution to use the `v120_xp` platform toolset, or add `/2013` to your VPC build scripts.

It would be up to VALVe to add `v142` support to the public SDK, but seeing as that's rather unlikely I welcome you to check out the Community Edition repo at Nbc66/source-sdk-2013-ce, where we will be adding `v142` support in the very near future.

Hope this helps.

* Since you can't install the VS2013 build tools separately.

**Comment by GamerDude27** [comment]
The only way to use VS2019 at the moment is by having both VS2013 and VS2019 installed at the same time*.
Once you have them both installed, you can either manually change all the projects in your solution to use the `v120_xp` platform toolset, or add `/2013` to your VPC build scripts.

It would be up to VALVe to add `v142` support to the public SDK, but seeing as that's rather unlikely I welcome you to check out the Community Edition repo at Nbc66/source-sdk-2013-ce, where we will be adding `v142` support in the very near future.

Hope this helps.

* Since you can't install the VS2013 build tools separately.

**Comment by KurtisCates** [comment]
https://github.com/Enhanced-Source-Project/Enhanced-Source
