### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by gkjohnson** [ValveSoftware/source-sdk-2013#509]
Hello! I have written a file loader for source film maker models in Javascript ([link to project](https://github.com/gkjohnson/source-engine-model-loader)) by referencing the data structures in this SDK and the source engine [wiki](https://developer.valvesoftware.com/wiki/MDL). I have currently released the Javascript under the MIT license but I want to make sure that that falls within the terms of the license or at least the spirit of the license outlined in this repo. I have not copied any SDK code just referenced the model header files to understand data structure layout, byte offsets, vertex data indirection, and vertex file fixup handling.

Thank you for your help!

**Comment by dbechrd** [comment]
Disclaimer: I'm not a lawyer, this is not professional legal advice, etc.

Data structures and file formats are not protected under copyright law in the United States. Only the code itself, as written, is able to be claimed. As long as your code is original, and especially if it's in another language entirely, it's legal.

Software licenses can only extend your right to use copyrighted code in a way that would normally be considered infringement. Since your usage is not infringement in the general case, the license terms are not relevant.

**Comment by gkjohnson** [comment]
Thanks for the perspective on licenses around data structures @dbechrd! I expected this was the case but it's good to have another take.

> you do need to be careful using "Valve", "Source Engine" or other similar brand-distinguishing trademarks in a way that might mislead people to believe you are an officially sanctioned affiliate of Valve

Appreciate this, as well - I've tried to make an effort to note that the project is unofficial and the models are copyright the respective owners (Valve) but of course am happy to adjust as needed if there are requests.
