### ISSUE TITLE
Push Source SDK 2013 Multiplayer Build 6630498 to the Github as a Release version.

### ISSUE THREAD

**Issue by SC1040-TS2** [ValveSoftware/source-sdk-2013#517]
While this sort of Issue request may require decoupling the MP branch from this Github page's codebase and setting up a new listing for it elsewhere, the notion of being able to push Builds as a Release version to better keep track of recent changes made to the SDK would be a novel and worthwhile thing to do.

This is especially true in the wake of the most recent patch to Source 2013 MP, which purportedly introduced several security and stability improvements that I am sure users would love to look into and learn more about given how sparse the details were on them.

However, again, to attempt to use Github's Release system would probably require some heavy reorganizing and decoupling of MP and SP codebases on Github, much as it is on Steam. This is, understandably, not very ideal.

**Comment by kisak-valve** [comment]
Hello @SC1040-TS2, there is already a request to update the SDK in this repo with the Valve internal code base at #359. Closing as a duplicate.

**Comment by SC1040-TS2** [comment]
> Hello @SC1040-TS2, there is already a request to update the SDK in this repo with the Valve internal code base at #359. Closing as a duplicate.

I understand. It is just another one in the wake of the aforementioned patch released this month.

**Comment by Adrianilloo** [comment]
@SC1040-TS2 The recent security update, as of related kind of updates, are likely to affect the internal engine's source code (with some exceptions, like the `strtok` buffer overflow fix around 2017), meaning we may not expect to see changes on the SDK. If you're curious, one of the noticeable things proving they'd have strived in security in the last update was the removal of the embed `libgcc_0.so.1` library of their base `bin` directory to use the one from system instead (this is a very fundamental library to the Linux Kernel). This means they analyzed the system one doesn't break compatibility with their custom binaries (server, client, engine-related), and then they can get the benefits that syncing with the system lib, accounting for future updates, has (e.g. security patches).

What's important, even more than gameplay related fixes, is that they urgently update dependent SDK libraries (static and/or dynamic ones) that are unsynced with the ones used in their base `bin` directory, because this randomly causes unexpected programming results that I've recently found that my own workaround (https://github.com/ValveSoftware/source-sdk-2013/pull/448#issuecomment-371980998) doesn't fix after all.
